---
- name: Fetch the latest Lazygit release version
  uri:
    url: https://api.github.com/repos/jesseduffield/lazygit/releases/latest
    return_content: yes
    headers:
      Accept: application/vnd.github.v3+json
  register: lazygit_release

- name: Set Lazygit version variable
  set_fact:
    lazygit_version: "{{ lazygit_release.json.tag_name | regex_replace('^v', '') }}"

- name: Download Lazygit tarball
  get_url:
    url: "https://github.com/jesseduffield/lazygit/releases/download/{{ lazygit_release.json.tag_name }}/lazygit_{{ lazygit_version }}_Linux_x86_64.tar.gz"
    dest: "/tmp/lazygit.tar.gz"

- name: Extract the Lazygit executable
  unarchive:
    src: "/tmp/lazygit.tar.gz"
    dest: "/tmp"
    remote_src: true
  register: extraction_result

- name: List files in /tmp after extraction
  command: ls -l /tmp
  when: extraction_result is changed

- name: Install Lazygit binary
  become: true
  command:
    cmd: install /tmp/lazygit /usr/local/bin
    creates: /usr/local/bin/lazygit
