- name: Install LunarVim
  shell: yes | LV_BRANCH='release-1.3/neovim-0.9' bash <(curl -s https://raw.githubusercontent.com/LunarVim/LunarVim/release-1.3/neovim-0.9/utils/installer/install.sh)

- name: Install language servers and formatters for LunarVim
  shell: lvim +LvimUpdate +LvimCacheReset +q
  ignore_errors: true